"""
app/services/comparison_service.py
───────────────────────────────────
FR3 — Section comparison generator.

Takes the original text chunks retrieved from the vector store and the
updated text generated by the LLM, and produces structured side-by-side
comparisons with a human-readable summary of changes.
"""

from __future__ import annotations

import logging
import re

from app.models.schemas import SectionComparison

logger = logging.getLogger(__name__)


# ── Public function ────────────────────────────────────────────────────────────

def build_section_comparisons(
    original_chunk_texts: list[str],
    original_metadata: list[dict],
    updated_text: str,
) -> list[SectionComparison]:
    """
    Build structured old-vs-new comparisons for each updated section.

    Matches sections between the original chunks and the updated text
    using heading detection and content overlap heuristics.

    Parameters
    ----------
    original_chunk_texts : List of original text chunks from the vector store.
    original_metadata    : Corresponding metadata dicts (for filename, index info).
    updated_text         : The full updated notes text from the LLM.

    Returns
    -------
    list[SectionComparison] — one per identifiable section.
    """
    comparisons: list[SectionComparison] = []

    # 1. Extract sections from original chunks
    original_sections = _extract_sections("\n\n".join(original_chunk_texts))

    # 2. Extract sections from updated text
    updated_sections = _extract_sections(updated_text)

    # 3. Match and compare sections
    if not original_sections:
        # No clear headings found; treat as a single monolithic section
        comparisons.append(
            SectionComparison(
                section_title="Full Document Section",
                original_text="\n\n".join(original_chunk_texts),
                updated_text=updated_text,
                changes_summary=_generate_changes_summary(
                    "\n\n".join(original_chunk_texts), updated_text
                ),
            )
        )
    else:
        for orig_title, orig_content in original_sections:
            matched_updated = _find_matching_section(
                orig_title, orig_content, updated_sections
            )
            changes = _generate_changes_summary(orig_content, matched_updated)

            comparisons.append(
                SectionComparison(
                    section_title=orig_title,
                    original_text=orig_content.strip(),
                    updated_text=matched_updated.strip(),
                    changes_summary=changes,
                )
            )

        # If any updated sections weren't matched, add them
        matched_titles = {c.section_title for c in comparisons}
        for upd_title, upd_content in updated_sections:
            if upd_title not in matched_titles:
                comparisons.append(
                    SectionComparison(
                        section_title=upd_title,
                        original_text="(New section — not in original notes)",
                        updated_text=upd_content.strip(),
                        changes_summary="This section was newly created during the update.",
                    )
                )

    return comparisons


# ── Internal helpers ───────────────────────────────────────────────────────────

def _extract_sections(text: str) -> list[tuple[str, str]]:
    """
    Split text into sections based on markdown headings.

    Returns list of (heading, content) pairs.
    """
    # Match any markdown heading: # ## ### etc
    heading_pattern = re.compile(r"^(#{1,6})\s+(.+)$", re.MULTILINE)

    sections: list[tuple[str, str]] = []
    last_pos = 0
    last_heading = "Introduction"

    for match in heading_pattern.finditer(text):
        if match.start() > last_pos:
            content = text[last_pos : match.start()].strip()
            if content:
                sections.append((last_heading, content))
        last_heading = match.group(2).strip()
        last_pos = match.end()

    # Last section
    remaining = text[last_pos:].strip()
    if remaining:
        sections.append((last_heading, remaining))

    if not sections and text.strip():
        sections.append(("Document", text.strip()))

    return sections


def _find_matching_section(
    orig_title: str,
    orig_content: str,
    updated_sections: list[tuple[str, str]],
) -> str:
    """
    Find the best-matching updated section for an original section.

    Tries exact title match first, then partial title match,
    then content overlap.
    """
    # 1. Exact title match
    for upd_title, upd_content in updated_sections:
        if upd_title.lower() == orig_title.lower():
            return upd_content

    # 2. Partial title match
    title_words = set(orig_title.lower().split())
    best_score = 0
    best_content = ""
    for upd_title, upd_content in updated_sections:
        upd_words = set(upd_title.lower().split())
        overlap = len(title_words & upd_words)
        if overlap > best_score:
            best_score = overlap
            best_content = upd_content

    if best_score > 0 and best_content:
        return best_content

    # 3. Content overlap
    orig_sentences = set(
        re.split(r"(?<=[.!?])\s+", orig_content.lower())
    )
    best_sentence_overlap = 0
    best_content_by_sentence = ""
    for upd_title, upd_content in updated_sections:
        upd_sentences = set(
            re.split(r"(?<=[.!?])\s+", upd_content.lower())
        )
        overlap = len(orig_sentences & upd_sentences)
        if overlap > best_sentence_overlap:
            best_sentence_overlap = overlap
            best_content_by_sentence = upd_content

    if best_content_by_sentence:
        return best_content_by_sentence

    # 4. Fallback — return the entire updated text
    if updated_sections:
        return "\n\n".join(c for _, c in updated_sections)
    return orig_content


def _generate_changes_summary(original: str, updated: str) -> str:
    """
    Generate a human-readable summary of what changed between original and updated.

    Uses simple heuristics: length changes, new terminology, structural changes.
    """
    if original == updated:
        return "No changes were made to this section."

    changes: list[str] = []

    orig_len = len(original.split())
    upd_len = len(updated.split())
    word_diff = upd_len - orig_len

    if abs(word_diff) > 5:
        direction = "expanded" if word_diff > 0 else "condensed"
        changes.append(
            f"Content {direction} from ~{orig_len} to ~{upd_len} words "
            f"({'+' if word_diff > 0 else ''}{word_diff} words)."
        )
    elif abs(word_diff) > 0:
        changes.append(f"Minor length adjustment ({word_diff:+d} words).")

    # Detect new technical terms (capitalised words that appear only in updated)
    orig_terms = set(re.findall(r"\b[A-Z][a-z]+(?:\s+[A-Z][a-z]+)*\b", original))
    upd_terms = set(re.findall(r"\b[A-Z][a-z]+(?:\s+[A-Z][a-z]+)*\b", updated))
    new_terms = upd_terms - orig_terms
    if new_terms:
        terms_preview = ", ".join(sorted(new_terms)[:5])
        changes.append(f"New concepts/terms introduced: {terms_preview}.")

    # Check structural changes (headings)
    orig_headings = set(re.findall(r"^#{1,6}\s.+$", original, re.MULTILINE))
    upd_headings = set(re.findall(r"^#{1,6}\s.+$", updated, re.MULTILINE))
    new_headings = upd_headings - orig_headings
    if new_headings:
        changes.append(f"New headings added: {len(new_headings)}.")

    if not changes:
        changes.append("Content refined for clarity and currency.")

    return " ".join(changes)